namespace SharpFM.Tests.CanonicalSkill;

/// <summary>
/// Fixtures whose current POCO output diverges from the skill's canonical
/// form. This is the divergence inventory surfaced in phase 2 — the baseline
/// the audit shrinks. As each step is migrated to the shape-driven renderer
/// (phases 5–6) and starts round-tripping, remove its fixture name here; the
/// round-trip test's guard will fail until you do, so the list cannot silently
/// drift out of sync with reality.
///
/// <para>
/// Entries are fixture base names (file name without extension). A trailing
/// <c>-N</c> marks one of several documented variants for the same step id
/// (e.g. configured vs unconfigured forms).
/// </para>
/// </summary>
public static class KnownDivergences
{
    public static readonly IReadOnlySet<string> Names = new HashSet<string>(StringComparer.Ordinal)
    {
        "003-SaveACopyAsXML-1",
        "003-SaveACopyAsXML-2",
        "004-GoToNextField",
        "005-GoToPreviousField",
        "011-InsertFromIndex",
        "012-InsertFromLastVisited",
        "013-InsertCurrentDate",
        "014-InsertCurrentTime",
        "017-GoToField-1",
        "018-CheckSelection",
        "026-OmitMultipleRecords",
        "035-ImportRecords",
        "036-ExportRecords",
        "037-SaveACopyAs",
        "040-RelookupFieldContents",
        "046-Cut",
        "047-Copy",
        "048-Paste",
        "049-Clear",
        "057-SendEvent",
        "060-InsertCurrentUserName",
        "061-InsertText",
        "062-PauseResumeScript",
        "065-DialPhone",
        "066-Speak",
        "067-PerformAppleScript",
        "076-SetField-1",
        "077-InsertCalculatedResult",
        "083-ChangePassword",
        "087-ShowCustomDialog-1",
        "087-ShowCustomDialog-2",
        "087-ShowCustomDialog-3",
        "089-Comment-1",
        "091-ReplaceFieldContents",
        "095-RecoverFile",
        "096-SaveACopyAsAddOnPackage",
        "097-SetZoomLevel-2",
        "103-ExitScript-1",
        "111-OpenURL",
        "116-SetNextSerialValue",
        "119-MoveResizeWindow",
        "121-CloseWindow-1",
        "123-SelectWindow",
        "124-SetWindowTitle",
        "128-PerformFindReplace",
        "130-SetSelection",
        "132-ExportFieldContents",
        "134-AddAccount",
        "135-DeleteAccount",
        "136-ResetAccountPassword",
        "137-EnableAccount",
        "138-ReLogin-1",
        "139-ConvertFile",
        "143-SaveRecordsAsExcel",
        "144-SaveRecordsAsPDF-1",
        "144-SaveRecordsAsPDF-2",
        "145-GoToObject-1",
        "145-GoToObject-2",
        "146-SetWebViewer-1",
        "146-SetWebViewer-2",
        "146-SetWebViewer-3",
        "147-SetFieldByName",
        "150-PerformQuickFind",
        "152-SaveRecordsAsSnapshotLink",
        "157-InstallPlugInFile",
        "161-InsertFromDevice",
        "167-RefreshObject-1",
        "167-RefreshObject-2",
        "175-PerformJavaScriptInWebViewer-1",
        "177-AVPlayerPlay",
        "179-AVPlayerSetOptions",
        "180-RefreshPortal",
        "181-GetFolderPath",
        "188-GetFileExists",
        "189-GetFileSize",
        "190-CreateDataFile",
        "191-OpenDataFile",
        "192-WriteToDataFile",
        "193-ReadFromDataFile",
        "194-GetDataFilePosition",
        "195-SetDataFilePosition",
        "196-CloseDataFile",
        "197-DeleteFile",
        "199-RenameFile",
        "200-SetErrorLogging",
        "203-ExecuteFileMakerDataAPI",
        "205-OpenTransaction",
        "207-RevertTransaction",
        "208-SetSessionIdentifier",
        "209-SetDictionary",
        "210-PerformScriptOnServerWithCallback",
        "211-TriggerClarisConnectFlow",
        "212-ConfigureAIAccount-1",
        "212-ConfigureAIAccount-2",
        "212-ConfigureAIAccount-3",
        "215-InsertEmbedding",
        "216-InsertEmbeddingInFoundSet",
        "225-SaveRecordsAsJSONL",
        "226-ConfigurePromptTemplate",
        "228-GoToListOfRecords",
    };
}
