namespace SharpFM.Tests.CanonicalSkill;

/// <summary>
/// Fixtures whose steps do NOT survive display-text mutation today (their
/// display grammar or FromDisplay parser is lossy) even though the step
/// claims <c>IsFullyEditable</c>. This is the display-accuracy worklist: as
/// each step's display pair becomes faithful — or the step is sealed instead —
/// remove its fixtures here; the round-trip test's guard fails until you do,
/// so the list cannot silently drift out of sync with reality.
/// </summary>
public static class KnownDisplayDivergences
{
    public static readonly IReadOnlySet<string> Names = new HashSet<string>(StringComparer.Ordinal)
    {
        "003-SaveACopyAsXML-2",
        "009-DeleteRecordRequest",
        "010-DeleteAllRecords",
        "011-InsertFromIndex",
        "012-InsertFromLastVisited",
        "013-InsertCurrentDate",
        "014-InsertCurrentTime",
        "017-GoToField-1",
        "018-CheckSelection",
        "028-PerformFind-2",
        "035-ImportRecords",
        "036-ExportRecords",
        "039-SortRecords-2",
        "040-RelookupFieldContents",
        "046-Cut",
        "047-Copy",
        "048-Paste",
        "049-Clear",
        "051-RevertRecordRequest",
        "057-SendEvent",
        "060-InsertCurrentUserName",
        "062-PauseResumeScript",
        "063-SendMail",
        "065-DialPhone",
        "066-Speak",
        "067-PerformAppleScript",
        "074-GoToRelatedRecord-1",
        "074-GoToRelatedRecord-2",
        "076-SetField-1",
        "087-ShowCustomDialog-1",
        "087-ShowCustomDialog-2",
        "091-ReplaceFieldContents",
        "097-SetZoomLevel-2",
        "099-GoToPortalRow-2",
        "104-DeletePortalRow",
        "116-SetNextSerialValue",
        "117-ExecuteSQL",
        "119-MoveResizeWindow",
        "121-CloseWindow-1",
        "121-CloseWindow-2",
        "122-NewWindow-1",
        "122-NewWindow-2",
        "126-ConstrainFoundSet-1",
        "126-ConstrainFoundSet-2",
        "128-PerformFindReplace",
        "131-InsertFile",
        "142-InstallMenuSet",
        "143-SaveRecordsAsExcel",
        "144-SaveRecordsAsPDF-1",
        "144-SaveRecordsAsPDF-2",
        "145-GoToObject-2",
        "157-InstallPlugInFile",
        "161-InsertFromDevice",
        "175-PerformJavaScriptInWebViewer-1",
        "177-AVPlayerPlay",
        "179-AVPlayerSetOptions",
        "182-TruncateTable",
        "185-ConfigureRegionMonitorScript",
        "187-ConfigureLocalNotification",
        "201-ConfigureNFCReading",
        "202-ConfigureMachineLearningModel",
        "211-TriggerClarisConnectFlow",
        "212-ConfigureAIAccount-1",
        "212-ConfigureAIAccount-2",
        "213-FineTuneModel",
        "214-PerformSQLQueryByNaturalLanguage",
        "218-PerformSemanticFind",
        "219-PerformRAGAction",
        "220-GenerateResponseFromModel",
        "221-PerformFindByNaturalLanguage",
        "222-ConfigureRegressionModel",
        "225-SaveRecordsAsJSONL",
        "227-ConfigureRAGAccount",
        "243-CreatePDF-1",
        "243-CreatePDF-2",
        "244-AppendPDF-2",
        "246-OpenPDF-2",
    };
}
