version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
  groups:
    NLog:
      patterns:
        - "NLog*"
    Avalonia:
      patterns:
        - "Avalonia*"
    MicrosoftCodeAnalysis:
      patterns:
        - "Microsoft.CodeAnalysis.*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updates to GitHub Actions every weekday
    interval: "daily"
    timezone: America/Chicago